# file: utilsay_install.yml
---
- name: Install util-say
  hosts: all
  gather_facts: yes
  become: true
  vars:
    dependencies: 
    - git
    - make
    - gcc
    - texinfo
  tasks:
  - name: Check for javac
    shell: 'javac -version 2>&1'
    register: javacheck
    ignore_errors: true

  - debug:
      var: javacheck

  - name: Download and install JDK 8 release 191
    block:
    - name: Download Oracle JDK
      get_url:
        url: 'http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.rpm'
        headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
        dest: '/tmp/jdk-8u191-linux-x64.rpm'
        checksum: sha1:e37712a8bb438712200bbbbd96a963e73975f43e
      retries: 3
      delay: 3

    - name: Install JDK
      yum:
        name: '/tmp/jdk-8u191-linux-x64.rpm'
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install JDK
      dnf:
        name: '/tmp/jdk-8u191-linux-x64.rpm'
        state: present
      when: ansible_distribution == "Fedora"

    - name: Clean up the JDK rpm
      file:
        path: '/tmp/jdk-8u191-linux-x64.rpm'
        state: absent
    when: javacheck.stdout != "javac 1.8.0_191"

  - name: Check for utilsay
    stat:
      path: '/usr/bin/ponytool'
    register: utilcheck

  - name: Download and install util-say
    block:
    - name: Install Git, make, gcc and textinfo on CentOS
      yum:
        name: '{{item}}'
        state: latest
      with_items: '{{ dependencies }}'
      when: ansible_distribution == "CentOS"

    - name: Install Git, make, gcc and textinfo on Fedora
      dnf:
        name: '{{item}}'
        state: latest
      with_items: '{{ dependencies }}'
      when: ansible_distribution == "Fedora"

    - name: Clone the util-say repo
      git:
        repo: 'https://github.com/maandree/util-say.git'
        dest: '/tmp/util-say'

    - name: Run make
      make:
        chdir: '/tmp/util-say'

    - name: Run make install
      make:
        chdir: '/tmp/util-say'
        target: install

    - name: Clean-up
      file:
        path: '/tmp/util-say'
        state: absent
    when: utilcheck.stat.exists == false
